In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print("Hello World!")

Hello World!


In [3]:
visible_units = 6

In [4]:
dataset_initial = np.array(
    [[1, 1, 0, 0, 0, 0],
     [0, 0, 1, 1, 0, 0],
     [0, 0, 0, 0, 1, 1],
     [1, 1, 0, 0, 0, 1],
     [0, 0, 1, 1, 0, 0],
     [0, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 1, 0],
     [1, 1, 0, 1, 0, 0],
     [1, 0, 1, 1, 0, 0],
     [0, 0, 1, 0, 1, 1]])
dataset_initial

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1]])

In [5]:
patterns = dataset_initial[0:3]
patterns

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1]])

function add_examples concatenates the amout of number_examples of random patterns generated by np.random.randint.

In [6]:
def add_examples (data, number_examples):
    return np.concatenate((data, np.random.randint(2, size = (number_examples, 6))))

Loops 10 times to add the patterns and random patterns.

In [7]:
dataset = add_examples(patterns, 5)
for i in range(10):
    dataset = np.concatenate((dataset, patterns))
    dataset = add_examples(dataset, 5)

In [8]:
dataset.shape

(88, 6)

In [9]:
dataset

array([[1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0],
 

Export created dataset to csv to be used on my RBM.

In [12]:
np.savetxt("../../c_lang/dataset/training_dataset.csv", dataset, fmt="%1.0f", delimiter=",")