In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
num_examples = 2
num_times = 30

In [15]:
num_layers = 2
num_hidden = 4

In [16]:
maxepochs = 1000
epsilonw = 0.01
epsilonvb = 0.01
epsilonhb = 0.01

In [17]:
def add_examples (data, num_examples, num_visible):
    return np.concatenate((data, 
                           np.random.randint(2, size = (num_examples, num_visible))))

In [18]:
pattern = np.array([[1,0,0,1,0,1,0,1,0]])

In [19]:
num_visible = pattern.shape[1]

In [20]:
dataset = add_examples(pattern, num_examples, num_visible)

for i in range(num_times):
    dataset = np.concatenate((dataset, pattern))
    dataset = add_examples(dataset, num_examples, num_visible)

In [21]:
dataset.shape

(93, 9)

In [22]:
unq, inv, cnt = np.unique(dataset, axis = 0,
                              return_inverse = True,
                              return_counts = True)

Each unique row present in the dataset

In [23]:
unq

array([[0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1,

Count of occurencies for each row, if repeated number is greater than 1.

In [24]:
inv

array([36, 51, 40, 36, 44, 21, 36,  2, 49, 36, 56, 46, 36, 18,  7, 36, 14,
       26, 36, 39, 31, 36, 25, 29, 36,  3, 17, 36, 28, 13, 36, 19, 38, 36,
       53, 50, 36, 22,  6, 36, 55, 24, 36, 43, 32, 36,  1, 15, 36, 58, 10,
       36,  9, 12, 36,  4, 54, 36,  4, 11, 36, 47, 20, 36, 49,  8, 36, 41,
       33, 36, 35, 45, 36, 52, 48, 36, 37, 46, 36,  5,  0, 36, 30, 23, 36,
       34, 57, 36, 16, 22, 36, 42, 27])

Count of each unique row in dataset.

In [25]:
cnt

array([ 1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 31,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  1])