In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
num_examples = 2
num_times = 30

In [3]:
num_layers = 2
num_hidden = 4

In [4]:
maxepochs = 1000
epsilonw = 0.01
epsilonvb = 0.01
epsilonhb = 0.01

In [5]:
def add_examples (data, num_examples, num_visible):
    return np.concatenate((data, 
                           np.random.randint(2, size = (num_examples, num_visible))))

In [6]:
pattern = np.array([[1,0,0,1,0,1,0,1,0]])

In [7]:
num_visible = pattern.shape[1]

In [8]:
dataset = add_examples(pattern, num_examples, num_visible)

for i in range(num_times):
    dataset = np.concatenate((dataset, pattern))
    dataset = add_examples(dataset, num_examples, num_visible)

In [9]:
dataset.shape

(93, 9)

In [10]:
unq, cnt = np.unique(dataset, axis = 0,
                              return_counts = True)

Each unique row present in the dataset

In [11]:
unq

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 1, 1,

Count of each unique row in dataset.

In [12]:
cnt

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 31,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  2,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1])

In [13]:
np.savetxt("../../c_lang/dataset/training_dataset_2.csv", dataset, fmt="%1.0f", delimiter=",")

In [14]:
dataset

array([[1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 0,